# Automatically generated by configure - do not modify
SRC_PATH=/home/parkhk/development/qemu_trace/qemu_v042013/qemu-1.3.0_singlestep_memtrace_lessinfo/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
