# Automatically generated by configure - do not modify
SRC_PATH=/home/parkhk/development/qemu_trace/run_qemu/qemu_hit_ratio_for_ssd_design/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
LD=ld
