# Automatically generated by configure - do not modify
SRC_PATH=/home/parkhk/development/k_fama_ISMM/qemu_write_trace/qemu_memtrace/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
# Automatically generated by configure - do not modify
SRC_PATH=/home/parkhk/development/k_fama_ISMM/qemu_write_trace/qemu_memtrace_network/roms/seabios
CC=gcc
BCC=bcc
CPP=cpp
OBJCOPY=objcopy
IASL=iasl
HOST_CC=gcc
LD=ld
